Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,3 +62,22 @@ jobs:
         echo "Starting the testing process"
         ./gradlew test
         echo "Testing process done."
+
+
+    - name: Make HTTP GET request with curl - to esm, for deployment
+      run: |
+          echo 'entered depeloy step' 
+          BASE_URL="https://5045-86-127-179-145.ngrok-free.app/deploy"
+          PARAMS="?vmType=cpu&repoUrl=https://github.com/beiuhori07/integrity-check.git&lastCommitHash=111"
+
+          echo 'right before curl'
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" "${BASE_URL}${PARAMS}")
+          echo 'right after curl'
+
+          if [[ ${RESPONSE} -ge 400 ]]; then
+            echo "HTTP error occurred: ${RESPONSE}"
+            cat response.json
+            exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
+          fi
+
+          echo "Success: ${RESPONSE}"
