Update redeployment.yml

diff --git a/.github/workflows/redeployment.yml b/.github/workflows/redeployment.yml
--- a/.github/workflows/redeployment.yml
+++ b/.github/workflows/redeployment.yml
@@ -1,27 +1,30 @@
 name: Manual redeployment workflow
 
-# Controls when the workflow will run
 on:
-  workflow_dispatch:  # Triggers the workflow manually
+  workflow_dispatch: 
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks out a copy of the repository
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      # Run a one-line script
-      - name: Run a Hello World script
-        run: echo "Hello, World!"
-
-      # Run additional commands
       - name: Run additional commands
         run: |
-          echo "This workflow is triggered manually."
-          echo "Running custom commands..."
+          echo 'entered redepeloy step' 
+          BASE_URL="https://2b9c96b1370aa52a594af09b1132090a.serveo.net/redeploy"
+          PARAMS="?vmType=$vmType&repoUrl=https://github.com/$GITHUB_REPOSITORY.git&lastCommitHash=$GITHUB_SHA"
+
+          echo 'right before curl'
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" "${BASE_URL}${PARAMS}")
+          echo 'right after curl'
+
+          if [[ ${RESPONSE} -ge 400 ]]; then
+            echo "HTTP error occurred: ${RESPONSE}"
+            cat response.json
+            exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
+          fi
+
+          echo "Success: ${RESPONSE}"
